version: '3.2'

services:

  byspolyservice:
    build:
      context: ./backend/laravel
      dockerfile: Dockerfile
    ports:
      - 3030:8000
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./backend/laravel:/app
    networks:
      - byspolynetwork

  mysql:
    image: mariadb:10.5.8
    environment:
      - MYSQL_ROOT_PASSWORD=Ubuxa##99
      - MYSQL_DATABASE=forge
      - MYSQL_USER=forge
      - MYSQL_PASSWORD=Ubuxa##99
    networks:
      - byspolynetwork

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 3031:80
    environment:
      - PMA_HOST=mysql
      - PMA_PASSWORD=Ubuxa##99
    restart: unless-stopped
    volumes:
    # Re-use local composer cache via host-volume
    - ~/.composer-docker/cache:/root/.composer/cache:delegated
    # Mount source-code for development
    - ./:/app
    networks:
      - byspolynetwork
  
networks:
  byspolynetwork:
    driver: bridge
