version: 2.1


jobs:
  deploy-student-staging:
    
    docker:
        - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
         fingerprints: 
          - "ca:1a:82:30:b6:07:92:c2:9e:25:cf:ac:0c:28:f9:dd"
      - checkout
      # install dependencies
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true
      # - run:
      #     name: Run npm 
      #     command: |
      #       CI=false cd frontend && npm install && npm run test
      - run:
          name: Run npm 
          command: |
            CI=false cd frontend_student && npm install 

      - run: CI=false sudo apt update
      - run: CI=false sudo apt-get install rsync

      - run:
          name: Update known hosts
          command: ssh-keyscan -H 185.160.67.60 >> ~/.ssh/known_hosts && cat ~/.ssh/known_hosts
      - run:
          name: rename .env.example file to .env 
          command: |
            mv frontend_student/.env.example frontend_student/.env
      - run:
          name: build file
          command: |
            cd frontend_student && CI=false npm run build 
     
      - run:
          name: ssh login  
          command: |
            rsync -va -e 'ssh -p 7822 -o StrictHostKeyChecking=no'  --delete   frontend_student/build/ frontend_student/.htaccess skillz@185.160.67.60:byspolye/student
      # - run:
      #     name: ssh and run migration on live server  
      #     command: |
      #       ssh bartumen@192.254.235.94 && cd devapi.bartumenergy.com &&  php artisan migrate && ls && exit
      
  deploy-admin-staging:
    
    docker:
        - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
         fingerprints: 
          - "ca:1a:82:30:b6:07:92:c2:9e:25:cf:ac:0c:28:f9:dd"
      - checkout
      # install dependencies
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true
      # - run:
      #     name: Run npm 
      #     command: |
      #       CI=false cd frontend && npm install && npm run test
      - run:
          name: Run npm 
          command: |
            CI=false cd frontend_admin && npm install 

      - run: CI=false sudo apt update
      - run: CI=false sudo apt-get install rsync

      - run:
          name: Update known hosts
          command: ssh-keyscan -H 185.160.67.60 >> ~/.ssh/known_hosts && cat ~/.ssh/known_hosts
      - run:
          name: rename .env.example file to .env 
          command: |
            mv frontend_admin/.env.example frontend_admin/.env
      - run:
          name: build file
          command: |
            cd frontend_admin && CI=false npm run build 
     
      - run:
          name: ssh login  
          command: |
            rsync -va -e 'ssh -p 7822 -o StrictHostKeyChecking=no'  --delete   frontend_admin/build/ frontend_admin/.htaccess skillz@185.160.67.60:byspolye/admin
      # - run:
      #     name: ssh and run migration on live server  
      #     command: |
      #       ssh bartumen@192.254.235.94 && cd devapi.bartumenergy.com &&  php artisan migrate && ls && exit
      
  deploy-laravel-staging:
    docker:
        - image: cimg/php:8.1
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints: 
          - "ca:1a:82:30:b6:07:92:c2:9e:25:cf:ac:0c:28:f9:dd"
      - checkout
      # install dependencies
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: cd backend/laravel && CI=false  composer install &&  CI=false php artisan key:generate

      - run: sudo apt update
      - run: sudo apt-get install rsync

      # - run:
      #     name: Update known hosts
      #     command:  CI=false ssh-keyscan -H 185.160.67.60 >> ~/.ssh/known_hosts && cat ~/.ssh/known_hosts
      - run:
          name: find and replace in document
          command: |
            sed -i -e 's:/public/index.php:/index.php:g' backend/laravel/public/index.php && sed -i -e 's:/../vendor/autoload.php:/vendor/autoload.php:g' backend/laravel/public/index.php && sed -i -e 's:DB_DATABASE=forge:DB_DATABASE=skillz_byspolye:g' backend/laravel/.env.example && sed -i -e 's:DB_USERNAME=forge:DB_USERNAME=skillz_tibilon:g' backend/laravel/.env.example  && sed -i -e 's:/../bootstrap/app.php:/bootstrap/app.php:g' backend/laravel/public/index.php && sed -i -e 's:DB_PASSWORD=forge:DB_PASSWORD="Ubuxa##99":g' backend/laravel/.env.example 

      - run:
          name: rename .env.example file to .env 
          command: |
            mv backend/laravel/.env.example backend/laravel/.env

      - run:
          name: ssh login  
          command: |
            cd backend/laravel && rsync --delete -va -e 'ssh -p 7822 -o StrictHostKeyChecking=no'   app database phpunit.xml storage vendor artisan .env tests bootstrap composer.json resources composer.lock routes config package.json public/ skillz@185.160.67.60:byspolye/api
            
workflows:
  version: 2
  Byspoly_deploy:
    jobs:
      - deploy-laravel-staging: # Use the pre-configured job, deploy-via-git
          filters:
            branches:
              only: staging
      - deploy-admin-staging: # Use the pre-configured job, deploy-via-git
          filters:
            branches:
              only: staging
      - deploy-student-staging:
          filters:
            branches:
              only: staging 
      